server:
  port: 9001
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username:
#    password:
logging:
  level:
    root: info
    org:
      springframework:
        transaction:
          interceptor: TRACE
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  aop:
    proxy-target-class: false
