spring:
  application:
    name: client1
  main:
    allow-bean-definition-overriding: true
#  cloud:
##    zookeeper:
##      connect-string: 192.168.207.133:2181
#    consul:
#      host: 192.168.207.133
#      port: 8500
#      discovery:
#        prefer-ip-address: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka
    registry-fetch-interval-seconds: 5
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    address: 192.168.0.126

waiter:
  services:
    - localhost:6002
    - localhost:6003

feign:
  hystrix:
    enabled: true
